name: Build, lint, test, and doc

on:
  push:
    branches: ["main", "cicd", "release", "develop"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  base:
    name: Build, check and test
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - nightly
        include:
          - toolchain: nightly
            components: rustfmt
          - toolchain: stable
            components: rustfmt, clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: ${{ matrix.components }}
      - name: Prepare
        if: matrix.toolchain != 'stable'
        run: |
          rustup toolchain install stable --no-self-update --component clippy
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          key: ubuntu-latest_${{ matrix.toolchain }}"
      - name: Build
        run: cargo build --all-features
      - name: Format
        run: cargo fmt -- --check
      - name: Lint
        run: cargo +stable clippy --all-features --all-targets -- -D warnings
        env:
          CARGO_REGISTRIES_CRATES_IO_PROTOCOL: git # unstable on 1.66 + 1.67
      - name: Test
        run: cargo test --all-features
   
  docs:
    needs: [base]
    name: Docs/ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Run doc tests
        run: cargo test --all-features --doc
      - name: Check Documentation
        run: cargo doc --all-features --no-deps --document-private-items