name: Run Fuzztest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  base:
    name: Fuzztest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - nightly
        include:
          - toolchain: nightly
            components: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: ${{ matrix.components }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ubuntu-latest_${{ matrix.toolchain }}
      - name: Build
        run: cargo build --all-features
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Fuzz rart_check for 30 seconds
        run: cargo fuzz run rart_check -- -max_total_time=30s
      - name: Fuzz rart_iter_range for 30 seconds
        run: cargo fuzz run rart_iter_range -- -max_total_time=30s
      - name: Fuzz versioned_tree_check for 30 seconds
        run: cargo fuzz run versioned_tree_check -- -max_total_time=30s
      - name: Fuzz versioned_tree_multithread for 30 seconds
        run: cargo fuzz run versioned_tree_multithread -- -max_total_time=30s
