name: Run Fuzztest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  base:
    name: Fuzztest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - nightly
        include:
          - toolchain: nightly
            components: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: ${{ matrix.components }}
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          key: ubuntu-latest_${{ matrix.toolchain }}"
      - name: Build
        run: cargo build --all-features
      - name: Get fuzzy for 30 seconds
        run: cargo fuzz run rart_check -- -max_total_time=30s
