name: Run Callgrind Microbenchmark

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  base:
    name: Build and run microbenchmarks
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - nightly
        include:
          - toolchain: nightly
            components: rustfmt
          - toolchain: stable
            components: rustfmt, clippy

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: ${{ matrix.components }}
      - name: Prepare
        if: matrix.toolchain != 'stable'
        run: |
          rustup toolchain install stable --no-self-update --component clippy
      - uses: Swatinem/rust-cache@v2.2.0
        with:
          key: ubuntu-latest_${{ matrix.toolchain }}"
      - name: Install valgrind
        run: sudo apt-get -y update && sudo apt-get -y install valgrind
      - name: Info
        run: |
          set -x
          uname -a
          pwd
          rustup --version
          rustup show
          rustup component list --installed
          valgrind --version
      - name: Install callgrind runner
        run: cargo install --version 0.3.1 iai-callgrind-runner
      - name: Bench
        run: cargo bench --all-features --bench art_iai_bench --bench node_mapping_iai_microbenches
