name: Run Criterion Benchmarks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  base:
    name: Build and run benchmarks
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - nightly
        include:
          - toolchain: nightly
            components: rustfmt
          - toolchain: stable
            components: rustfmt, clippy

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: ${{ matrix.components }}
      - name: Prepare
        if: matrix.toolchain != 'stable'
        run: |
          rustup toolchain install stable --no-self-update --component clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: ubuntu-latest_${{ matrix.toolchain }}
      - name: Info
        run: |
          set -x
          uname -a
          pwd
          rustup --version
          rustup show
          rustup component list --installed
      - name: Bench
        run: cargo bench --all-features --bench art_bench --bench art_compare_bench --bench node_mapping_microbenches
